theme: jekyll-theme-minimal

gem "github-pages", group: :jekyll_plugins

title: Xing Su's Homepage

description: [Xing Su 苏醒\ PhD Candidate in the Department of Computing, Macquarie University (MQ), Sydney, Australia.]

logo: profile.jpg

show_downloads: false
