theme: jekyll-theme-minimal

gem "github-pages", group: :jekyll_plugins

title: Xing Su's Homepage

description: [Hi，I'm Xing Su，a PhD Candidate in the Department of Computing，Macquarie University. It's nice to meet you!]

logo: profile.jpg

show_downloads: false
